run:
  timeout: 5m
  issues-exit-code: 1
  tests: true
  build-tags:
  skip-dirs:
    - internal/restsigner/signer

linters-settings:
  gocyclo:
    min-complexity: 15

linters:
  enable:
    - deadcode
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - revive
    - gosimple
    - govet
    - ineffassign
    - misspell
    - exportloopref
    - staticcheck
    - structcheck
    - typecheck
    - unconvert
    - varcheck
  disable-all: true
